// This file exists to generate the code needed to make
// dunedaq::networkqueue::fsd::FakeData usable in
// QueueToNetworkAdapterDAQModule and
// NetworkToQueueAdapterDAQModule. It has to be compiled with
// daq_add_plugin() in the CMakeLists.txt, with a line like this:
//
//    daq_add_plugin( FakeData duneNetworkQueue TEST LINK_LIBRARIES networkqueue )
//
// The generated plugin is used inside a
// QueueToNetworkAdapterDAQModule or
// NetworkToQueueAdapterDAQModule. Pass these parameters
// to that module at init time:
//
//     "msg_type": "dunedaq::networkqueue::fsd::FakeData",
//     "msg_module_name": "FakeData",
//
// where the "msg_type" matches the argument to
// DEFINE_DUNE_NETWORKQUEUE, and the "msg_module_name" is the plugin
// name given to daq_add_plugin


// This include is for the DEFINE_DUNE_NETWORKQUEUE macro used below
#include "networkqueue/NetworkQueueMacros.hpp"

// These includes are for the definition of the FakeData class and the
// code to serialize it to MsgPack and JSON formats. In this case, the
// includes are all generated by moo, but they do not need to be
#include "networkqueue/fsd/Structs.hpp"
#include "networkqueue/fsd/Nljs.hpp"
#include "networkqueue/fsd/MsgP.hpp"

DEFINE_DUNE_NETWORKQUEUE(dunedaq::networkqueue::fsd::FakeData)
